//keys:
const FI_type="type";
const FI_id="id";
const FI_userlabel="userlabel";
const FI_ptpId="ptpId";
const FI_ptpUserlabel="ptpUserlabel";
const FI_neId="neId";
const FI_neUserlabel="neUserlabel";
const FI_cardId="cardId";
const FI_cardUserlabel="cardUserlabel";
const FI_dir="dir";
const FI_aTP="aTP";
const FI_zTP="zTP";
const FI_yNode0="yNode0";
const FI_yNode1="yNode1";
//values:
const FI_type_XC="XC";
const FI_type_CTP="CTP";
const FI_type_PTP="PTP";
const FI_type_CONNECTION="CONNECTION";
const FI_type_yNode="yNode";
const FI_dir_BI="BI";
const FI_dir_UNI="UNI";

const flowInfo2=[
	{
        "type":"CTP",
        "id":"BDBL-PSS32-ROADM-26/260SCX2-5-4-C1/dsr=1",
        "userlabel":"260SCX2-5-4-C1/dsr=1",
        "ptpId":"BDBL-PSS32-ROADM-26/260SCX2-5-4-C1",
        "ptpUserlabel":"260SCX2-5-4-C1",
        "neId":"BDBL-PSS32-ROADM-26",
        "neUserlabel":"BDBL-PSS32-ROADM-26",
        "cardId":"BDBL-PSS32-ROADM-26/260SCX2-5-4",
        "cardUserlabel":"260SCX2-5-4"
    },
    {
        "type":"XC",
        "id":"xc_1",
        "userlabel":"xxx",
        "dir":"BI",
        "aTP":[
            "BDBL-PSS32-ROADM-26/260SCX2-5-4-C1/dsr=1"
        ],
        "zTP":[
            "BDBL-PSS32-ROADM-26/260SCX2-5-4-L1/ODU4=1"
        ]
    },
    {
        "type":"CTP",
        "id":"BDBL-PSS32-ROADM-26/260SCX2-5-4-L1/ODU4=1",
        "userlabel":"260SCX2-5-4-L1/ODU4=1",
        "ptpId":"BDBL-PSS32-ROADM-26/260SCX2-5-4-L1",
        "ptpUserlabel":"260SCX2-5-4-L1",
        "neId":"BDBL-PSS32-ROADM-26",
        "neUserlabel":"BDBL-PSS32-ROADM-26",
        "cardId":"BDBL-PSS32-ROADM-26/260SCX2-5-4",
        "cardUserlabel":"260SCX2-5-4"
    },
    {
        "type":"CONNECTION",
        "id":"conn_1",
        "userlabel":"xxx",
        "dir":"BI",
        "aTP":[
            "BDBL-PSS32-ROADM-26/260SCX2-5-4-L1"
        ],
        "zTP":[
            "BDBL-PSS32-ROADM-26/OPSA-5-3-SIG"
        ]
    },
    {
        "type":"CTP",
        "id":"BDBL-PSS32-ROADM-26/OPSA-5-3-SIG/frequency=1",
        "userlabel":"OPSA-5-3-SIG/frequency=1",
        "ptpId":"BDBL-PSS32-ROADM-26/OPSA-5-3-SIG",
        "ptpUserlabel":"OPSA-5-3-SIG",
        "neId":"BDBL-PSS32-ROADM-26",
        "neUserlabel":"BDBL-PSS32-ROADM-26",
        "cardId":"BDBL-PSS32-ROADM-26/OPSA-5-3",
        "cardUserlabel":"OPSA-5-3"
    },
    {
        "type":"XC",
        "id":"xc_2",
        "userlabel":"xxx",
        "dir":"BI",
        "aTP":[
            "BDBL-PSS32-ROADM-26/OPSA-5-3-SIG/frequency=1"
        ],
        "zTP":[
            "BDBL-PSS32-ROADM-26/OPSA-5-3-A/frequency=1",
			"BDBL-PSS32-ROADM-26/OPSA-5-3-B/frequency=1"
        ]
    },
	{
        "type":"yNode",
        "yNode0":[
            {
                "type":"CTP",
                "id":"BDBL-PSS32-ROADM-26/OPSA-5-3-A/frequency=1",
                "userlabel":"OPSA-5-3-A/frequency=1",
                "ptpId":"BDBL-PSS32-ROADM-26/OPSA-5-3-A",
                "ptpUserlabel":"OPSA-5-3-A",
                "neId":"BDBL-PSS32-ROADM-26",
                "neUserlabel":"BDBL-PSS32-ROADM-26",
                "cardId":"BDBL-PSS32-ROADM-26/OPSA-5-3",
                "cardUserlabel":"OPSA-5-3"
            },
            {
                "type":"CONNECTION",
                "id":"conn_3",
                "userlabel":"xxx",
                "dir":"BI",
                "aTP":[
                    "BDBL-PSS32-ROADM-26/OPSA-5-3-A"
                ],
                "zTP":[
                    "BDBL-PSS32-ROADM-26/SFD44-26-1-9475"
                ]
            },
            {
                "type":"CTP",
                "id":"BDBL-PSS32-ROADM-26/SFD44-26-1-9475/frequency=1",
                "userlabel":"SFD44-26-1-9475/frequency=1",
                "ptpId":"BDBL-PSS32-ROADM-26/SFD44-26-1-9475",
                "ptpUserlabel":"SFD44-26-1-9475",
                "neId":"BDBL-PSS32-ROADM-26",
                "neUserlabel":"BDBL-PSS32-ROADM-26",
                "cardId":"BDBL-PSS32-ROADM-26/SFD44-26-1",
                "cardUserlabel":"SFD44-26-1"
            },
            {
				"type":"XC",
				"id":"xc_1",
				"userlabel":"xxx",
				"dir":"BI",
				"aTP":[
					"BDBL-PSS32-ROADM-26/SFD44-26-1-9475/frequency=1"
				],
				"zTP":[
					"BDBL-PSS32-ROADM-26/SFD44-26-1-OMD/frequency=9475"
				]
			},
            {
                "type":"CTP",
                "id":"BDBL-PSS32-ROADM-26/SFD44-26-1-OMD/frequency=9475",
                "userlabel":"SFD44-26-1-OMD/frequency=9475",
                "ptpId":"BDBL-PSS32-ROADM-26/SFD44-26-1-OMD",
                "ptpUserlabel":"SFD44-26-1-OMD",
                "neId":"BDBL-PSS32-ROADM-26",
                "neUserlabel":"BDBL-PSS32-ROADM-26",
                "cardId":"BDBL-PSS32-ROADM-26/SFD44-26-1",
                "cardUserlabel":"SFD44-26-1"
            },
			{
				"type":"yNode",
				"yNode0":[
					{
						"type":"CTP",
						"id":"BDBL-PSS32-ROADM-26/SFD44-26-1-OMD/frequency=9475",
						"userlabel":"SFD44-26-1-OMD/frequency=9475",
						"ptpId":"BDBL-PSS32-ROADM-26/SFD44-26-1-OMD",
						"ptpUserlabel":"SFD44-26-1-OMD",
						"neId":"BDBL-PSS32-ROADM-26",
						"neUserlabel":"BDBL-PSS32-ROADM-26",
						"cardId":"BDBL-PSS32-ROADM-26/SFD44-26-1",
						"cardUserlabel":"SFD44-26-1"
					},
					{
						"type":"CONNECTION",
						"id":"conn_3",
						"userlabel":"xxx",
						"dir":"UNI",
						"aTP":[
							"BDBL-PSS32-ROADM-26/SFD44-26-1-OMD"
						],
						"zTP":[
							"BDBL-PSS32-ROADM-26/WR8-88AF-1-4-ADDIN2"
						]
					},
					{
						"type":"PTP",
						"id":"BDBL-PSS32-ROADM-26/WR8-88AF-1-4-ADDIN2",
						"userlabel":"WR8-88AF-1-4-ADDIN2",
						"ptpId":"BDBL-PSS32-ROADM-26/WR8-88AF-1-4-ADDIN2",
						"ptpUserlabel":"WR8-88AF-1-4-ADDIN2",
						"neId":"BDBL-PSS32-ROADM-26",
						"neUserlabel":"BDBL-PSS32-ROADM-26",
						"cardId":"BDBL-PSS32-ROADM-26/WR8-88AF-1-4",
						"cardUserlabel":"WR8-88AF-1-4"
					}
				],
				"yNode1":[
					{
						"type":"CTP",
						"id":"BDBL-PSS32-ROADM-26/SFD44-26-1-OMD/frequency=9475",
						"userlabel":"SFD44-26-1-OMD/frequency=9475",
						"ptpId":"BDBL-PSS32-ROADM-26/SFD44-26-1-OMD",
						"ptpUserlabel":"SFD44-26-1-OMD",
						"neId":"BDBL-PSS32-ROADM-26",
						"neUserlabel":"BDBL-PSS32-ROADM-26",
						"cardId":"BDBL-PSS32-ROADM-26/SFD44-26-1",
						"cardUserlabel":"SFD44-26-1"
					},
					{
						"type":"CONNECTION",
						"id":"conn_3",
						"userlabel":"xxx",
						"dir":"UNI",
						"aTP":[
							"BDBL-PSS32-ROADM-26/ITL-25-1-OUT"
						],
						"zTP":[
							"BDBL-PSS32-ROADM-26/SFD44-26-1-OMD"
						]
					},
					{
						"type":"PTP",
						"id":"BDBL-PSS32-ROADM-26/ITL-25-1-OUT",
						"userlabel":"ITL-25-1-OUT",
						"ptpId":"BDBL-PSS32-ROADM-26/ITL-25-1-OUT",
						"ptpUserlabel":"ITL-25-1-OUT",
						"neId":"BDBL-PSS32-ROADM-26",
						"neUserlabel":"BDBL-PSS32-ROADM-26",
						"cardId":"BDBL-PSS32-ROADM-26/ITL-25-1",
						"cardUserlabel":"ITL-25-1"
					},
					{
						"type":"XC",
						"id":"xc_1",
						"userlabel":"xxx",
						"dir":"UNI",
						"aTP":[
							"BDBL-PSS32-ROADM-26/ITL-25-1-SIGIN"
						],
						"zTP":[
							"BDBL-PSS32-ROADM-26/ITL-25-1-OUT"
						]
					},
					{
						"type":"PTP",
						"id":"BDBL-PSS32-ROADM-26/ITL-25-1-SIGIN",
						"userlabel":"ITL-25-1-SIGIN",
						"ptpId":"BDBL-PSS32-ROADM-26/ITL-25-1-SIGIN",
						"ptpUserlabel":"ITL-25-1-SIGIN",
						"neId":"BDBL-PSS32-ROADM-26",
						"neUserlabel":"BDBL-PSS32-ROADM-26",
						"cardId":"BDBL-PSS32-ROADM-26/ITL-25-1",
						"cardUserlabel":"ITL-25-1"
					},
					{
						"type":"CONNECTION",
						"id":"conn_3",
						"userlabel":"xxx",
						"dir":"UNI",
						"aTP":[
							"BDBL-PSS32-ROADM-26/WR8-88AF-1-4-DROPOUT"
						],
						"zTP":[
							"BDBL-PSS32-ROADM-26/ITL-25-1-SIGIN"
						]
					},
					{
						"type":"PTP",
						"id":"BDBL-PSS32-ROADM-26/WR8-88AF-1-4-DROPOUT",
						"userlabel":"WR8-88AF-1-4-DROPOUT",
						"ptpId":"BDBL-PSS32-ROADM-26/WR8-88AF-1-4-DROPOUT",
						"ptpUserlabel":"WR8-88AF-1-4-DROPOUT",
						"neId":"BDBL-PSS32-ROADM-26",
						"neUserlabel":"BDBL-PSS32-ROADM-26",
						"cardId":"BDBL-PSS32-ROADM-26/WR8-88AF-1-4",
						"cardUserlabel":"WR8-88AF-1-4"
					}
				]
			}
        ],
		"yNode1":[
            {
                "type":"CTP",
                "id":"BDBL-PSS32-ROADM-26/OPSA-5-3-B/frequency=1",
                "userlabel":"OPSA-5-3-B/frequency=1",
                "ptpId":"BDBL-PSS32-ROADM-26/OPSA-5-3-B",
                "ptpUserlabel":"OPSA-5-3-B",
                "neId":"BDBL-PSS32-ROADM-26",
                "neUserlabel":"BDBL-PSS32-ROADM-26",
                "cardId":"BDBL-PSS32-ROADM-26/OPSA-5-3",
                "cardUserlabel":"OPSA-5-3"
            },
            {
                "type":"CONNECTION",
                "id":"conn_3",
                "userlabel":"xxx",
                "dir":"BI",
                "aTP":[
                    "BDBL-PSS32-ROADM-26/OPSA-5-3-B"
                ],
                "zTP":[
                    "BDBL-PSS32-ROADM-26/SFD44-29-1-9475"
                ]
            },
            {
                "type":"CTP",
                "id":"BDBL-PSS32-ROADM-26/SFD44-29-1-9475/frequency=1",
                "userlabel":"SFD44-29-1-9475/frequency=1",
                "ptpId":"BDBL-PSS32-ROADM-26/SFD44-29-1-9475",
                "ptpUserlabel":"SFD44-29-1-9475",
                "neId":"BDBL-PSS32-ROADM-26",
                "neUserlabel":"BDBL-PSS32-ROADM-26",
                "cardId":"BDBL-PSS32-ROADM-26/SFD44-29-1",
                "cardUserlabel":"SFD44-29-1"
            },
            {
				"type":"XC",
				"id":"xc_1",
				"userlabel":"xxx",
				"dir":"BI",
				"aTP":[
					"BDBL-PSS32-ROADM-26/SFD44-29-1-9475/frequency=1"
				],
				"zTP":[
					"BDBL-PSS32-ROADM-26/SFD44-29-1-OMD/frequency=9475"
				]
			},
            {
                "type":"CTP",
                "id":"BDBL-PSS32-ROADM-26/SFD44-29-1-OMD/frequency=9475",
                "userlabel":"SFD44-29-1-OMD/frequency=9475",
                "ptpId":"BDBL-PSS32-ROADM-26/SFD44-29-1-OMD",
                "ptpUserlabel":"SFD44-29-1-OMD",
                "neId":"BDBL-PSS32-ROADM-26",
                "neUserlabel":"BDBL-PSS32-ROADM-26",
                "cardId":"BDBL-PSS32-ROADM-26/SFD44-29-1",
                "cardUserlabel":"SFD44-29-1"
            }
        ]
    }
]
const flowInfo=[
    {
        "type":"CTP",
        "id":"ctp_1",
        "userlabel":"C1/dsr=1",
        "ptpId":"ptp_1",
        "ptpUserlabel":"C1",
        "neId":"ne_1",
        "neUserlabel":"NE_1",
        "cardId":"card_1",
        "cardUserlabel":"CARD_1"
    },
    {
        "type":"XC",
        "id":"xc_1",
        "userlabel":"xxx",
        "dir":"BI",
        "aTP":[
            "ctp_1"
        ],
        "zTP":[
            "ctp_2"
        ]
    },
    {
        "type":"CTP",
        "id":"ctp_2",
        "userlabel":"L1/odu2=1",
        "ptpId":"ptp_2",
        "ptpUserlabel":"L1",
        "neId":"ne_1",
        "neUserlabel":"NE_1",
        "cardId":"card_1",
        "cardUserlabel":"CARD_1"
    },
    {
        "type":"CONNECTION",
        "id":"conn_1",
        "userlabel":"xxx",
        "dir":"BI",
        "aTP":[
            "ptp_2"
        ],
        "zTP":[
            "ptp_3"
        ]
    },
    {
        "type":"CTP",
        "id":"ctp_3",
        "userlabel":"SFD-9600/frequency=1",
        "ptpId":"ptp_3",
        "ptpUserlabel":"SFD-9600",
        "neId":"ne_2",
        "neUserlabel":"NE_2",
        "cardId":"card_2",
        "cardUserlabel":"CARD_2"
    },
    {
        "type":"XC",
        "id":"xc_2",
        "userlabel":"xxx",
        "dir":"UNI",
        "aTP":[
            "ctp_3"
        ],
        "zTP":[
            "ctp_4"
        ]
    },
    {
        "type":"CTP",
        "id":"ctp_4",
        "userlabel":"SFD-OMD/9600=1",
        "ptpId":"ptp_4",
        "ptpUserlabel":"SFD-OMD",
        "neId":"ne_2",
        "neUserlabel":"NE_2",
        "cardId":"card_2",
        "cardUserlabel":"CARD_2"
    },
    {
        "type":"CONNECTION",
        "id":"conn_2",
        "userlabel":"xxx",
        "dir":"UNI",
        "aTP":[
            "ptp_4"
        ],
        "zTP":[
            "ptp_5"
        ]
    },
    {
        "type":"CTP",
        "id":"ctp_5",
        "userlabel":"OPSA-1-SIG/oms=1",
        "ptpId":"ptp_5",
        "ptpUserlabel":"OPSA-1-SIG",
        "neId":"ne_2",
        "neUserlabel":"NE_2",
        "cardId":"card_3",
        "cardUserlabel":"CARD_3"
    },
    {
        "type":"XC",
        "id":"xc_3",
        "userlabel":"xxx",
        "dir":"UNI",
        "aTP":[
            "ctp_5"
        ],
        "zTP":[
            "ctp_6",
            "ctp_7"
        ]
    },
    {
        "type":"yNode",
        "yNode0":[
            {
                "type":"CTP",
                "id":"ctp_6",
                "userlabel":"OPSA-1-A/oms=1",
                "ptpId":"ptp_6",
                "ptpUserlabel":"OPSA-1-A",
                "neId":"ne_2",
                "neUserlabel":"NE_2",
                "cardId":"card_3",
                "cardUserlabel":"CARD_3"
            },
            {
                "type":"CONNECTION",
                "id":"conn_3",
                "userlabel":"xxx",
                "dir":"BI",
                "aTP":[
                    "ptp_6"
                ],
                "zTP":[
                    "ptp_61"
                ]
            },
            {
                "type":"PTP",
                "id":"ptp_61",
                "userlabel":"AHPHG-1-SIG",
                "ptpId":"ptp_61",
                "ptpUserlabel":"AHPHG-1-SIG",
                "neId":"ne_2",
                "neUserlabel":"NE_2",
                "cardId":"card_4",
                "cardUserlabel":"CARD_4"
            },
            {
                "type":"CONNECTION",
                "id":"conn_31",
                "userlabel":"xxx",
                "dir":"BI",
                "aTP":[
                    "ptp_61"
                ],
                "zTP":[
                    "ptp_62"
                ]
            },
            {
                "type":"CTP",
                "id":"ctp_62",
                "userlabel":"AHPHG-X-SIG/oms=1",
                "ptpId":"ptp_62",
                "ptpUserlabel":"AHPHG-X-SIG",
                "neId":"ne_2",
                "neUserlabel":"NE_2",
                "cardId":"card_4",
                "cardUserlabel":"CARD_4"
            }
        ],
        "yNode1":[
            {
                "type":"CTP",
                "id":"ctp_7",
                "userlabel":"OPSA-1-B/oms=1",
                "ptpId":"ptp_7",
                "ptpUserlabel":"OPSA-1-B",
                "neId":"ne_2",
                "neUserlabel":"NE_2",
                "cardId":"card_3",
                "cardUserlabel":"CARD_3"
            },
            {
                "type":"CONNECTION",
                "id":"conn_4",
                "userlabel":"xxx",
                "dir":"UNI",
                "aTP":[
                    "ptp_7"
                ],
                "zTP":[
                    "ptp_71"
                ]
            },
            {
                "type":"CTP",
                "id":"ctp_71",
                "userlabel":"AHPHG-2-SIG/oms=1",
                "ptpId":"ptp_71",
                "ptpUserlabel":"AHPHG-2-SIG",
                "neId":"ne_2",
                "neUserlabel":"NE_2",
                "cardId":"card_5",
                "cardUserlabel":"CARD_5"
            }
        ]
    },
    {
        "type":"XC",
        "id":"xc_99",
        "userlabel":"xxx",
        "dir":"BI",
        "aTP":[
            "ctp_9"
        ],
        "zTP":[
            "ctp_62",
            "ctp_71"
        ]
    },
    {
        "type":"CTP",
        "id":"ctp_9",
        "userlabel":"AHPHG-11-LINE/oms=1",
        "ptpId":"ptp_91",
        "ptpUserlabel":"AHPHG-11-LINE",
        "neId":"ne_2",
        "neUserlabel":"NE_2",
        "cardId":"card_5",
        "cardUserlabel":"CARD_5"
    }
]